deployment_targets:
- backup_path: ./backups/dev
  deployment_path: ./deploy/dev
  environment: dev
  health_check_url: /healthz
  host: 127.0.0.1
  max_downtime_seconds: 60
  name: development
  port: 8000
  rollback_enabled: true
- backup_path: /opt/backups/staging
  deployment_path: /opt/klerno-staging
  environment: staging
  health_check_url: /healthz
  host: staging.klerno.com
  max_downtime_seconds: 30
  name: staging
  port: 8000
  rollback_enabled: true
- backup_path: /opt/backups/production
  deployment_path: /opt/klerno-production
  environment: production
  health_check_url: /healthz
  host: klerno.com
  max_downtime_seconds: 10
  name: production
  port: 443
  rollback_enabled: true
notifications:
  email_recipients:
  - admin@klerno.com
  notify_on_deployment: true
  notify_on_failure: true
  notify_on_success: false
  slack_webhook: ''
pipeline_stages:
- commands:
  - python -m flake8 app/ --max-line-length=120 --ignore=E501,W503
  - python -m black app/ --check --diff
  continue_on_failure: false
  name: lint_and_format
  timeout_seconds: 180
- artifacts:
  - security_report.json
  commands:
  - python -m bandit -r app/ -f json -o security_report.json
  - python -m safety check --json
  continue_on_failure: true
  name: security_scan
  timeout_seconds: 300
- artifacts:
  - coverage.xml
  - htmlcov/
  commands:
  - python -m pytest app/tests/ -v --tb=short --cov=app --cov-report=xml --cov-report=html
  continue_on_failure: false
  name: unit_tests
  timeout_seconds: 600
- commands:
  - python enterprise_test_complete.py
  continue_on_failure: false
  name: integration_tests
  timeout_seconds: 300
- artifacts:
  - dist/
  commands:
  - python setup.py sdist bdist_wheel
  - python -m pip wheel . -w dist/
  continue_on_failure: false
  name: build_package
  timeout_seconds: 180
- commands:
  - docker build -t klerno-labs:latest .
  - docker tag klerno-labs:latest klerno-labs:$(git rev-parse --short HEAD)
  continue_on_failure: true
  name: docker_build
  timeout_seconds: 600
quality_gates:
  code_coverage_threshold: 80
  performance_test_threshold_ms: 1000
  security_scan_max_high: 0
  security_scan_max_medium: 5
