version: "3.8"

services:
  app:
    build:
      context: .
      target: runtime
    environment:
      - APP_ENV=production
      - PORT=8000
      - HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://klerno:klerno@db:5432/klerno}
      - JWT_SECRET=${JWT_SECRET:?set-a-strong-secret-in-env}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    volumes:
      - ./data:/app/data

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-klerno}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-klerno}
      POSTGRES_DB: ${POSTGRES_DB:-klerno}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - app

volumes:
  pgdata:
