# Prometheus Configuration for Klerno Labs
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "klerno_rules.yml"

scrape_configs:
  # Klerno Application Metrics
  - job_name: 'klerno-app'
    static_configs:
      - targets: ['klerno-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Klerno Monitoring Dashboard
  - job_name: 'klerno-monitoring'
    static_configs:
      - targets: ['klerno-monitoring:8080']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx Metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093