[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F"]
ignore = [
  "E402",  # allow imports after module vars in some modules
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["app"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
strict_optional = true
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
pretty = true
mypy_path = ["."]
# Start focused; can widen later
files = [
  "app/iso20022_compliance.py",
  "app/crypto_iso20022_integration.py",
]
