services:
  - type: web
    name: klerno-labs
    runtime: docker
    repo: https://github.com/Klerno-Labs/Klerno-Labs
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      # Allow Render to inject PORT; app honors ${PORT} in Dockerfile CMD
      # HOST defaults to 0.0.0.0 in Dockerfile, no need to override here
      - key: READINESS_FAIL_OPEN
        value: "1"
      - key: STATIC_VERSION
        # Render exposes RENDER_GIT_COMMIT or RENDER_GIT_COMMIT_SHA depending on runtime; use the latter if available
        # This ensures immutable, versioned assets per deploy
        value: ${RENDER_GIT_COMMIT_SHA}
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
