services:
  - type: web
    name: klerno-labs
    runtime: docker
    repo: https://github.com/Klerno-Labs/Klerno-Labs
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: ""
      - key: REDIS_URL
        value: ""
