from __future__ import annotations

from typing import Any

class Client:
    def __init__(
        self,
        server: tuple[str, int] | list[tuple[str, int]] | Any,
        *,
        timeout: int | None = ...,
    ) -> None: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: bytes, time: int | None = ...) -> None: ...
    def delete(self, key: str) -> None: ...
    def flush_all(self) -> None: ...
