name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy
      - name: Lint (ruff)
        run: |
          ruff check app/iso20022_compliance.py
          ruff check app/store.py
          ruff check app/notifications.py app/paywall.py app/security_session.py
          ruff check app/routes/render_test.py app/performance_optimization.py app/resilience_system.py
          ruff check app/system_monitor.py app/subscriptions.py
          ruff check app/main.py app/websocket_alerts.py
          ruff check app/integrations/xrp.py
          ruff check app/integrations/bsc.py
          ruff check app/auth.py
          ruff check app/enterprise_security_enhanced.py app/enterprise_security.py
          ruff check app/enterprise_monitoring.py
          ruff check app/llm.py app/models.py
          ruff check app/main_integration.py
      - name: Typecheck (mypy)
        run: mypy
      - name: Run tests
        run: pytest -q
      - name: ISO endpoint smoke
        run: python scripts/ci_smoke.py
