name: CI

on:
  push:
    branches: ["main", "cleanup/tests-ci"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          pip install pytest mypy flake8

      - name: Run tests
        run: python -m pytest -q

      - name: Run flake8 (lint)
        run: python -m flake8 --max-line-length=120 app
        continue-on-error: true

      - name: Run mypy (type checks)
        run: python -m mypy app --config-file mypy.ini || true
        # allow existing type issues while we gradually fix them
