name: CI
# Unified CI for lint, type-checks, and tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          # Ensure key dev tools are present even if not pinned
          pip install pytest-cov bandit

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Type check (mypy)
        run: python -m mypy . --hide-error-codes --no-color-output

      - name: Test with coverage (pytest)
        env:
          PYTHONWARNINGS: ignore
        run: pytest -q --cov=app --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Security scan (Bandit)
        run: bandit -q -r app -x tests
