name: CI (deprecated)

# Disabled from auto triggers to avoid duplicate/legacy runs blocking PRs.
# Use workflow_dispatch to run manually if ever needed.
on:
  workflow_dispatch: {}

jobs:
  test:
    if: ${{ false }} # fully disabled; kept for reference
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Legacy CI workflow disabled; use core-ci.yml instead."
