name: CI

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: CI

        on:
          push: {}
          pull_request: {}

        jobs:
          test:
            runs-on: ubuntu-latest
            strategy:
              matrix:
                python-version: ["3.11"]

            steps:
              - name: Checkout
                uses: actions/checkout@v4

              - name: Set up Python
                uses: actions/setup-python@v4
                with:
                  python-version: ${{ matrix.python-version }}

              - name: Cache pip
                uses: actions/cache@v4
                with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                    ${{ runner.os }}-pip-

              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
                  if [ -f dev-requirements.txt ]; then python -m pip install -r dev-requirements.txt; fi

              - name: Run mypy (type checks)
                run: |
                  python -m mypy --show-error-codes --pretty --ignore-missing-imports app tests || true

              - name: Run tests
                run: |
                  python -m pytest -q
