name: CI
# Unified CI for lint, type-checks, and tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          # Ensure key dev tools are present even if not pinned
          pip install pytest-cov bandit

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Type check (mypy)
        run: python -m mypy . --hide-error-codes --no-color-output

      - name: Test with coverage (pytest)
        env:
          PYTHONWARNINGS: ignore
        run: |
          # Ensure a fallback DATABASE_URL is available for tests and persist it
          mkdir -p ./data || true
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL=sqlite:///./data/klerno.db" >> $GITHUB_ENV
          else
            # persist whatever DATABASE_URL the job has so later steps see it
            echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
          fi
          # Install sqlalchemy for the initializer and run repo-provided init
          python -m pip install --upgrade pip sqlalchemy >/dev/null || true
          python -m scripts.init_db_if_needed || true
          pytest -q --cov=app --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Security scan (Bandit)
        run: bandit -q -r app -x tests
