name: Cleanup and Test

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Install test dependencies
              run: |
                  pip install pytest==7.4.0
                  pip install prometheus-client PyJWT pytest-asyncio

            - name: Cleanup tmp DBs (cross-platform)
              run: python scripts/cleanup_tmpdbs.py

            - name: Run tests
              id: run_tests
              continue-on-error: true
              run: python -m pytest -q

            - name: Upload DB artifacts on failure
              if: ${{ steps.run_tests.outcome == 'failure' }}
              uses: actions/upload-artifact@v4
              with:
                  name: forensic-dbs
                  path: |
                      tmp_*.db
                      **/tmp_*.db
