name: Weekly Dependency Audit

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          pip install pip-audit
      - name: Run pip-audit
        run: |
          set -e
          pip-audit -r requirements.txt -f json -o audit-runtime.json || true
          if [ -f dev-requirements.txt ]; then pip-audit -r dev-requirements.txt -f json -o audit-dev.json || true; fi
      - name: Summarize
        run: |
          echo 'Runtime vulnerabilities:'
          grep -o '"severity": "[A-Z]*"' audit-runtime.json | sort | uniq -c || true
          if [ -f audit-dev.json ]; then echo 'Dev vulnerabilities:'; grep -o '"severity": "[A-Z]*"' audit-dev.json | sort | uniq -c || true; fi
      - name: Upload audit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-audit-${{ github.run_id }}
          path: |
            audit-runtime.json
            audit-dev.json
          if-no-files-found: warn
