name: Klerno Labs Enterprise Production

on:
  push:
    branches: [main]
  pull_request:
    # Allow PR validation from feature branches including ci/enterprise-run-migrations-pr25
    branches: [main, "**"]
  workflow_dispatch:

concurrency:
  group: klerno-enterprise-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enterprise-validation:
    name: Enterprise Application Validation
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      APP_ENV: production
      PORT: 8002
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install runtime deps into the runner Python interpreter
          python -m pip install -r requirements.txt
          # Install test/dev deps if available, otherwise ensure pytest is installed
          if [ -f dev-requirements.txt ]; then
            python -m pip install -r dev-requirements.txt
          else
            python -m pip install pytest
          fi

      - name: Run DB migrations
        run: |
          # Ensure database schema is created before running integration tests.
          # Install alembic and create the local data directory used by sqlite.
          python -m pip install --upgrade alembic
          mkdir -p ./data
          mkdir -p .run
          # If CI didn't set DATABASE_URL, fall back to a local sqlite file.
          if [ -z "$DATABASE_URL" ]; then
            export DATABASE_URL="sqlite:///./data/klerno.db"
          fi
          # Run alembic pointing explicitly at the repo alembic.ini so the
          # migrations use the correct configuration in CI. Capture verbose
          # output to .run/alembic.log for debugging on failure.
          echo "=== alembic current ===" > .run/alembic.log || true
          python -m alembic -c alembic.ini current >> .run/alembic.log 2>&1 || true
          echo "=== alembic upgrade head ===" >> .run/alembic.log || true
          # Try upgrade; if it fails, attempt a safe stamp+upgrade fallback
          set -o pipefail || true
          python -m alembic -c alembic.ini upgrade head >> .run/alembic.log 2>&1 || (
            echo "alembic upgrade failed; attempting stamp head and retry" >> .run/alembic.log 2>&1 || true
            python -m alembic -c alembic.ini stamp head >> .run/alembic.log 2>&1 || true
            python -m alembic -c alembic.ini upgrade head >> .run/alembic.log 2>&1 || true
          )
          set +o pipefail || true

      - name: Run Enterprise Application Tests
        run: |
          python -m pytest tests/ -v --tb=short

      - name: Validate Enterprise Features
        run: |
          python -c "
          import sys
          sys.path.append('.')
          try:
              from enterprise_config import get_config, get_enabled_features
              config = get_config()
              features = get_enabled_features()
              print(f'Enterprise features: {len(features)}')
              assert len(features) >= 6, 'Must have 6+ enterprise features'
              print('✅ Enterprise validation passed')
          except Exception as e:
              print(f'❌ Enterprise validation failed: {e}')
              sys.exit(1)
          "

      - name: Security Scan
        run: |
          pip install bandit safety
          bandit -r app/ -f json -o security-report.json || true
          safety check --json || true

      - name: Upload migration logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alembic-logs
          path: .run/alembic.log
          if-no-files-found: warn

      - name: "Fallback: initialize DB schema if alembic failed"
        if: always()
        run: |
          # Run our lightweight initializer to ensure required tables exist
          python -m pip install --upgrade pip
          python -m pip install sqlalchemy
          python scripts/init_db_if_needed.py || true

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: enterprise-validation
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t klerno-enterprise:latest .

      - name: Test Docker Container
        run: |
          docker run -d --name klerno-test -p 8002:8002 klerno-enterprise:latest
          sleep 10
          curl -f http://localhost:8002/health || exit 1
          docker stop klerno-test
