name: Release Smoke Tests

on:
  workflow_dispatch:
    inputs:
      staging_url:
        description: 'Staging URL to test (https://...)'
        required: false
  push:
    tags:
      - 'v*.*.*'

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run prod smoke test
        # STAGING_URL should be provided either as a workflow_dispatch input (for manual runs)
        # or as a repository secret STAGING_URL for tag-triggered runs.
        run: |
          mkdir -p .run || true
          # prefer workflow_dispatch input when present
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.staging_url }}" ]; then
            URL="${{ github.event.inputs.staging_url }}"
          else
            if [ -z "${{ secrets.STAGING_URL }}" ]; then
              echo 'Provide staging_url via workflow_dispatch input or set STAGING_URL secret' && exit 2
            fi
            URL="${{ secrets.STAGING_URL }}"
          fi
          python tools/prod_smoke_test.py --url "$URL" --token-file .run/dev_tokens.json > .run/release-smoke.txt 2>&1 || true

      - name: Upload smoke artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-smoke
          path: .run/release-smoke.txt
          if-no-files-found: warn

      - name: Fail detection
        id: detect
        run: |
          set -e
          status="no-output"
          if [ -f .run/release-smoke.txt ]; then
            if grep -q "FAIL" .run/release-smoke.txt || grep -q "ERROR" .run/release-smoke.txt; then
              status="failed"
            else
              status="ok"
            fi
          fi
          echo "smoke_status=$status" >> $GITHUB_OUTPUT
          mkdir -p .run || true
          echo "$status" > .run/smoke-status.txt
