name: ruff-format

on:
    pull_request:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: true
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Install ruff
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff
            - name: Run ruff check
              run: |
                  python -m ruff check .
            - name: Run ruff format (fix on manual dispatch)
              if: github.event_name == 'workflow_dispatch'
              run: |
                  python -m ruff format --fix .
                  if [ -n "$(git status --porcelain)" ]; then
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git add -A
                    git commit -m "chore: ruff format --fix (CI)"
                    git push
                  else
                    echo "No formatting changes to commit"
                  fi
