name: Smoke Tests

on:
  push:
    branches: [ main, master, chore/dev-dx ]
  pull_request:
    branches: [ main, master, chore/dev-dx ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install test deps (if present)
        run: |
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run smoke tests
        run: |
          echo "Running smoke tests (tests/test_smoke.py)"
          pytest -q tests/test_smoke.py

      - name: Report success
        if: success()
        run: echo "Smoke tests passed ✅"
